### ISSUE TITLE
Exemplo de uso

### ISSUE THREAD

**Issue by hfleury** [Trust-Code/python-cnab#21]
Tudo bem?
Tem como me passar um exemplo de uso para me ajudar a implementar no meu sistema?

**Comment by danimaribeiro** [comment]
Segue
https://github.com/Trust-Code/odoo-brasil/tree/10.0/br_cnab/febraban

**Comment by terraze** [comment]
Olá @danimaribeiro , quais funcionalidades deste pacote? Estou tentando ler um CNAB400 mas não consegui obter os dados do mesmo (o arquivo não possui lotes e todas as linhas começam com '1').

```python
arquivo = {'arquivo': io.open(filePath, 'r', encoding='utf-8')}
from cnab240.bancos import bradesco_cobranca_400
dados = Arquivo(bradesco_cobranca_400,**arquivo)
print(dados.header.nome_do_banco)
# retorna o nome do banco, OK
print(dados.lotes())
# retorna [], OK
```
Como eu poderia obter um array com os registros contidos no arquivo? Analisei o código e não encontrei atribuição ou retorno de valores dos eventos sem relação com lotes.

**Comment by MatheusVp2** [comment]
Como eu poderia obter um array com os registros contidos no arquivo? Analisei o código e não encontrei atribuição ou retorno de valores dos eventos sem relação com lotes.


Realmente nao tem nada sobre ! Como pegar as informações do lote !
