### ISSUE TITLE
valor_titulo - campo:valor_titulo formato:num decimais:2 digitos:15 - valor:0

### ISSUE THREAD

**Issue by hfleury** [Trust-Code/python-cnab#23]
Pessoal, esta acontecendo esse erro.
Estou criando a lista e estou colocando assim 
'valor_titulo': Decimal(str(20.98)).quantize(Decimal('1.00')),
Como tem no exemplo da odoo. 
Consegue me ajudar?

**Comment by danimaribeiro** [comment]
Qual erro?

**Comment by hfleury** [comment]
Desculpa o do titulo
valor_titulo - campo:valor_titulo formato:num decimais:2 digitos:15 -
valor:0
E coloquei como esta no git, como no.exemplo do odoo

**Comment by danimaribeiro** [comment]
Ainda não entendi, deve ter outra mensagem junto.

**Comment by hfleury** [comment]
Variable Value self

Error in formatting: TipoError: campo:valor_titulo formato:num
decimais:2 digitos:15 - valor:0

valor

0

site-packages/cnab240/registro.py in valor linha 42

**Comment by danimaribeiro** [comment]
Acho que vai depender do banco que você está testando.
Ta vendo este formato do sicoob:
https://github.com/Trust-Code/python-cnab/blob/master/cnab240/bancos/sicoob/specs/segment_p.json#L160

Aqui diz que o campo valor_titulo é do tipo decimal, mas pode ser que outro banco o spec dele esteja errado ou diferente.

**Comment by hfleury** [comment]
Companheiro fiz alguns teste aqui colocando esse valor de forma estatica e passando como Decimal.
Estou tentando gerar uma remessa de pagamento do Santander.
1 - Eu gero o header o que esta indo corretamento
2 - Eu faço um for para passar por todas as ordens de pagamento colocar no dict e chamar o **incluir_cobranca**
3 - Eu faço a criação do arquivo .rem dou um open nele e quando eu chamo o metodo escrever do objeto Arquivo e nessa hora ele me gera esse erro.
Para testar eu criei um dicionario e sai colocando a maioria das informações estaticas como passo ai em baixo e coloquei negrito a valor_titulo, estou passando ele como decimal e continua a dar erro.
return {
            'controle_banco': 033,
            'cedente_agencia': 0,
            'cedente_conta': 12345,
            'cedente_conta_dv': 1,
            'cedente_agencia_dv': 1,
            'cedente_nome': u"teste fornecedor 30 casas     ",
            # DV ag e cc
            'cedente_dv_ag_cc': 12376,
            'identificacao_titulo': u'0000000',  # TODO
            'identificacao_titulo_banco': u'0000000',  # TODO
            'identificacao_titulo_empresa': (' ' * 25),
            'numero_documento': remessa.id,
            'vencimento_titulo': int(u"{0:%Y%m%d}".format(agora)),
            **'valor_titulo': Decimal(str(20.98)).quantize(Decimal('1.00')),**
            # TODO: Código adotado para identificar o título de cobrança.
            # 8 é Nota de cŕedito comercial
            'especie_titulo': 0,
            'aceite_titulo': 0,
            'data_emissao_titulo': int(u"{0:%Y%m%d}".format(agora)),
            # Taxa de juros do Odoo padrão mensal: 2. Campo 27.3P
            # CEF/FEBRABAN e Itaú não tem.
            'codigo_juros': 2,
            'juros_mora_data': int(u"{0:%Y%m%d}".format(agora)),
            'juros_mora_taxa': Decimal(str(12.00)).quantize(Decimal('1.00')),
            # Multa padrão em percentual no Odoo, valor '2'
            'codigo_multa': '2',
            'data_multa': int(u"{0:%Y%m%d}".format(agora)),
            'juros_multa': Decimal(str(15.00)).quantize(Decimal('1.00')),
            # TODO Remover taxa dia - deixar apenas taxa normal
            'juros_mora_taxa_dia': Decimal('0.00'),
            'valor_abatimento': Decimal('0.00'),
            'sacado_inscricao_tipo': int(1 if destino.ehCPF() else 2 if destino.ehCNPJ() else 3),
            'sacado_inscricao_numero': int(destino.cpf_cnpj_numerico()),
            'sacado_nome': 'teste fornecedor 30 casas      ',
            'sacado_endereco': (
                'Rua Francisco Antonio de Oliveira' + ' ' + '793  '),
            'sacado_bairro': 'Santa monica',
            'sacado_cep': destino.get_cep_prefixo(),
            'sacado_cep_sufixo': destino.get_cep_sufixo(),
            'sacado_cidade': "Uberlândia          ",
            'sacado_uf': "MG",
            'codigo_protesto': 00000,
            'prazo_protesto': 5,
            'codigo_baixa': 2,
            'prazo_baixa': 0,  # De 5 a 120 dias.
            'controlecob_data_gravacao': int(u"{0:%Y%m%d}".format(agora)),
            'cobranca_carteira': 00,
        }
