### ISSUE TITLE
Santander - CNAB240 - Pagamento a Fornecedores

### ISSUE THREAD

**Issue by victorguimaraessilva** [Trust-Code/python-cnab#35]
Olá pessoa, estou tentando implementar o arquivo de remessa de pagamentos a fornecedor, porém o JSON não bate quando é pagamento a fornecedores, alguem tem um exemplo de como fazer o uso da lib pra criar arquivos de pagamento a fornecedor? Logo no header algumas posições não sao iguais ao HeaderArquivo de cobrança.

Obrigado desde já =)

**Comment by danimaribeiro** [comment]
Vai ser necessário um refactor na lib para trabalhar com os dois.
Não tem exemplo.
