### ISSUE TITLE
Issue on validation of cnab240 in banco Itau

### ISSUE THREAD

**Issue by yk2kus** [Trust-Code/python-cnab#55]
Hello Danimar, 
I exported cnab240 (python3) using this repo. Client validated the file in the bank and got the error "T 3 1 19.06 18:35 19.06 18:35 NAO PROCES

011 SUMMARY OF FILE LINES DIFFER FROM TOTAL REG."

I believe, after fixing this issue there will be more. So I am willing to fix it for Itau. My concern is how do I validate my work? If I give to client and he gets me to return after a day with only. Is there a way I can do my tests and on having issue how do I know which line and which position the issue is?

Thanks in advance.

**Comment by yk2kus** [comment]
@danimaribeiro looking to hear from you.

**Comment by danimaribeiro** [comment]
You have to send the file to the bank, get the errors from them and fix, after that send it again.
Keep doing that until you finish the errors.

> Is there a way I can do my tests and on having issue how do I know which line and which position the issue is

You have to look at the manual, the only way.
